package com.example.mines_sweeper.controller;

import com.example.mines_sweeper.gridLogic.Level1_Grid;
import com.example.mines_sweeper.gridLogic.Level2_Grid;
import com.example.mines_sweeper.gridLogic.Timer;
import com.example.mines_sweeper.gridLogic.logic;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.layout.GridPane;

import java.net.URL;
import java.util.ResourceBundle;

public class Level2_Controller implements Initializable {

    private Level2_Grid level2Grid;
    private Timer timer;
    private final int level = 2;
    private int clickedRow,clickedCol;
    private boolean isGameOver;
    private boolean firstClick;
    @FXML
    public GridPane gridPane;

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        // Generate the grid with bomb
        level2Grid = new Level2_Grid();
        timer = new Timer();
        firstClick = true;
        isGameOver = false;
        level2Grid.displayGrid();
    }


    @FXML
    public void tilesClicked(ActionEvent event){

        // if game over
        if(isGameOver) return;


        Button clickedButton = (Button) event.getSource();


        assert clickedButton != null;
        String id = clickedButton.getId();
        clickedRow = id.charAt(7) - '0';
        clickedCol = id.charAt(8) - '0';


        if(level2Grid.isTileClicked(clickedRow,clickedCol)){
            System.out.println("already clicked");
            return;
        }


        if(firstClick){
            timer.start();
            if(level2Grid.isContainsBomb(clickedRow,clickedCol)){
                level2Grid.changeBombPosition(clickedRow,clickedCol);
            }

            level2Grid.zeroClearingTile(gridPane,clickedRow,clickedCol);
        }

        if(level2Grid.isContainsBomb(clickedRow,clickedCol)){
            System.out.println("bomb!!");
            isGameOver = true;
            // display all the bombs
            // errors generated by ikonli
            //level1Grid.displayBombs(gridPane);
            // load the lose panel fxml
            logic.loadFxmlModal("losePanel.fxml",event,level,timer.getElapsedTime());
        }
        else if(level2Grid.isTileFLagged(clickedRow,clickedCol)){
            level2Grid.changeTileUnclicked(clickedRow,clickedCol);
        }
        else {
            // valid tile clicked

            level2Grid.incrementSaveClicked();
            level2Grid.changeTileClicked(clickedRow,clickedCol);
            level2Grid.setTextOnButton(clickedButton,clickedRow,clickedCol);
        }

        // checking for win
        if(level2Grid.checkForWon()){
            System.out.println("You won!!!");
            // count the time
            timer.stop();
            System.out.println("Time : "+timer.getElapsedTime());
            isGameOver = true;
            logic.loadFxmlModal("winPanel.fxml",event,level,timer.getElapsedTime());
            // save it in a file further with name

        }
        firstClick = false;
        level2Grid.displayGrid();
    }

}
