package com.example.mines_sweeper.controller;

import com.example.mines_sweeper.gridLogic.*;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.layout.GridPane;

import java.net.URL;
import java.util.ResourceBundle;

public class level1_controller implements Initializable {

    private Level1_Grid level1Grid;
    private Timer timer;
    private int clickedRow,clickedCol;
    private boolean isGameOver;
    private boolean firstClick;
    @FXML
    public GridPane gridPane;

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        // Generate the grid with bomb
        level1Grid = new Level1_Grid();
        timer = new Timer();
        firstClick = true;
        isGameOver = false;
        level1Grid.displayGrid();
    }
    @FXML
    public void tilesClicked(ActionEvent event){


        // if game over
        if(isGameOver) return;


        Button clickedButton = (Button) event.getSource();
        String id = clickedButton.getId();
        clickedRow = id.charAt(7) - '1';
        clickedCol = id.charAt(8) - '1';

        if(level1Grid.isTileClicked(clickedRow,clickedCol)){
            System.out.println("already clicked");
            return;
        }

        // after the first click if it found bomb then switch it somewhere else in the same row
        if(firstClick){
            if(level1Grid.isContainsBomb(clickedRow,clickedCol)){
                level1Grid.changeBombPosition(clickedRow,clickedCol);
            }
            timer.start();
            // show the grids which number is 0
            level1Grid.zeroClearingTile(gridPane,clickedRow,clickedCol);
        }

        if(level1Grid.isContainsBomb(clickedRow,clickedCol)){
            System.out.println("bomb!!");
            isGameOver = true;
            // display all the bombs
            // errors generated by ikonli
            //level1Grid.displayBombs(gridPane);
        }
        else if(level1Grid.isTileFLagged(clickedRow,clickedCol)){
            level1Grid.changeTileUnclicked(clickedRow,clickedCol);
        }
        else {
            // valid tile clicked
            level1Grid.incrementSaveClicked();
            level1Grid.setTextOnButton(clickedButton,clickedRow,clickedCol);
        }

        // checking for win
        if(level1Grid.checkForWon()){
            System.out.println("You won!!!");
            // count the time
            timer.stop();
            System.out.println("Time : "+timer.getElapsedTime());
            isGameOver = true;
            // save it in a file further with name

        }
        firstClick = false;
        level1Grid.displayGrid();
    }
}