package com.example.mines_sweeper.controller;

import com.example.mines_sweeper.gridLogic.Level1_Grid;
import com.example.mines_sweeper.gridLogic.logic;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.layout.GridPane;

import java.net.URL;
import java.util.ResourceBundle;

public class level1_controller implements Initializable {

    private Level1_Grid level1Grid;
    private int clickedRow,clickedCol;
    private boolean isGameOver;
    private boolean firstClick;
    @FXML
    public GridPane gridPane;

    @Override
    public void initialize(URL url, ResourceBundle resourceBundle) {
        // Generate the grid with bomb
        level1Grid = new Level1_Grid();
        firstClick = true;
        isGameOver = false;
        level1Grid.displayGrid();
    }
    @FXML
    public void tilesClicked(ActionEvent event){

        // if game over or the tile is clicked
        if(isGameOver) return;
        if(level1Grid.isTileClicked(clickedRow,clickedCol)){
            return;
        }


        Button clickedButton = (Button) event.getSource();
        String id = clickedButton.getId();
        clickedRow = id.charAt(7) - '1';
        clickedCol = id.charAt(8) - '1';

        // after the first click if it found bomb then switch it somewhere else in the same row
        if(firstClick && level1Grid.isContainsBomb(clickedRow,clickedCol)){
            level1Grid.changeBombPosition(clickedRow,clickedCol);
            firstClick = false;
        }

        if(level1Grid.isContainsBomb(clickedRow,clickedCol)){
            System.out.println("bomb!!");
            isGameOver = true;
            // display all the bombs
            // errors generated by ikonli
            //level1Grid.displayBombs(gridPane);
        }
        else if(level1Grid.isTileFLagged(clickedRow,clickedCol)){
            level1Grid.changeTileUnclicked(clickedRow,clickedCol);
        }
        else {
            String color = logic.generateRandomColor();
            String css = "-fx-background-color: transparent;" +
                    "-fx-font-size:44px;-fx-font-weight:bold;" +
                    "-fx-text-fill:"+color+";";
            clickedButton.setStyle(css);

            level1Grid.incrementSaveClicked();
            int number = level1Grid.getGridNumber(clickedRow,clickedCol);
            clickedButton.setText(String.valueOf(number));
        }

        // checking for win
        if(level1Grid.checkForWon()){
            System.out.println("You won!!!");
            // count the time
            // save it in a file further with name
        }
    }
}